name: expense_tracker
description: Advanced Expense Tracker Flutter Application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  easy_date_timeline: ^2.0.9
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_expandable_fab: ^2.5.2
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.4.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  table_calendar: ^3.0.9
  uuid: ^4.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # Assets (jika ada)
  # assets:
  #   - images/
  #   - icons/
  # Fonts (jika ingin custom fonts)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
